export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const SET_LOADING = 'SET_LOADING'

export const SET_LOADING_DATA = 'SET_LOADING_DATA'

export const SET_LOADING_ERROR = 'SET_LOADING_ERROR'
